import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-100`}>
      <nav className="bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 px-8 py-4 shadow-lg border-b border-gray-800">
        <ul className="flex gap-8 font-semibold text-lg text-white">
        <li>
          <Link
          href="/"
          className="transition-colors duration-200 hover:text-blue-400"
          >
          Home
          </Link>
        </li>
        <li>
          <Link
          href="/users"
          className="transition-colors duration-200 hover:text-blue-400"
          >
          Users
          </Link>
        </li>
        <li>
          <Link
          href="/blog"
          className="transition-colors duration-200 hover:text-blue-400"
          >
          Blog
          </Link>
        </li>
        <li>
          <Link
          href="/categories"
          className="transition-colors duration-200 hover:text-blue-400"
          >
          Categories
          </Link>
        </li>
        </ul>
      </nav>
      <main className="max-w-3xl mx-auto py-8 px-4">{children}</main>
      </body>
    </html>
  );
}